swagger:
  title: 物资管理系统接口文档
  description: 物资管理系统-分类&供应商&物资管理接口
  exclude-path: /error # 剔除请求

server:
  port: 8001
  servlet:
    context-path: /wms # 上下文件路径，请求前缀 ip:port/wms

spring:
  application:
    name: wms-server # 应用名
  # 数据源配置
  datasource:
    username: root
    password:
    url: jdbc:mysql://127.0.0.1:3306/wms_university?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    #mysql8版本以上驱动包指定新的驱动类
    driver-class-name: com.mysql.cj.jdbc.Driver
    #   数据源其他配置, 在 DruidConfig配置类中手动绑定
    initialSize: 8
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL

mybatis-plus:
  type-aliases-package: cn.hzk.entities
  # xxxMapper.xml 路径
  mapper-locations: classpath*:cn/hzk/wms/mapper/**/*.xml

# 日志级别，会打印sql语句
logging:
  level:
    cn.hzk.goods.mapper: debug

mengxuegu:
  blog:
    # 阿里云配置
    aliyun:
      # 要带上 https:// ,上传时要使用的
      endpoint: https://oss-cn-shenzhen.aliyuncs.com
      accessKeyId: xxxxxx # 根据自己的帐号配置
      accessKeySecret: xxxxx # 根据自己的帐号配置
      bucketName: hzk # 存储空间名称
      # Bucket域名，访问文件时作为URL前缀，注意要加上 https:// 和 结尾带上 /
      bucketDomain: https://BUG-Hunter.oss-cn-shenzhen.aliyuncs.com/


